name: Build AlgoFin APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          # Adicionada a variável para ignorar o aviso de root
          options: >-
            -e BUILDOZER_WARN_ON_ROOT=0
            -v ${{ github.workspace }}:/home/user/hostcwd
          run: |
            cd /home/user/hostcwd
            buildozer android debug

      - name: Verificar APK
        run: |
          echo "APKs encontrados:"
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlgoFin-APK
          path: bin/*.apk
