name: Build AlgoFin APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          # Defina BUILDOZER_ALLOW_ROOT=1 para evitar o prompt interativo de root
          options: -e BUILDOZER_ALLOW_ROOT=1
          run: |
            buildozer android debug

      - name: Verificar APK
        run: |
          echo "APKs encontrados:"
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AlgoFin-APK
          path: bin/*.apk
